# Generated by Django 4.0.1 on 2022-02-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
    ]
