# Generated by Django 4.0.1 on 2022-02-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_blog', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
