# Generated by Django 4.0.1 on 2022-02-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_blog', '0003_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('science', 'Science'), ('tech', 'Tech'), ('health', 'Health'), ('fashion', 'Fashion'), ('beauty', 'Beauty'), ('arts & lifestyle', 'Arts & Lifesyle'), ('news', 'News'), ('fiction', 'Fiction')], max_length=20),
        ),
    ]
